"""add pending actions and customer conversations

Revision ID: f23bfa143b2c
Revises: 3f402650df1d
Create Date: 2026-07-26 01:27:29.203485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23bfa143b2c'
down_revision: Union[str, Sequence[str], None] = '3f402650df1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('external_user_id', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('schedule_request_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['schedule_request_id'], ['schedule_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_conversations_company_id'), 'customer_conversations', ['company_id'], unique=False)
    op.create_index(op.f('ix_customer_conversations_customer_email'), 'customer_conversations', ['customer_email'], unique=False)
    op.create_index(op.f('ix_customer_conversations_external_user_id'), 'customer_conversations', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_customer_conversations_status'), 'customer_conversations', ['status'], unique=False)
    op.create_table('customer_conversation_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['customer_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_conversation_messages_conversation_id'), 'customer_conversation_messages', ['conversation_id'], unique=False)
    op.add_column('chat_sessions', sa.Column('pending_action', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'pending_action')
    op.drop_index(op.f('ix_customer_conversation_messages_conversation_id'), table_name='customer_conversation_messages')
    op.drop_table('customer_conversation_messages')
    op.drop_index(op.f('ix_customer_conversations_status'), table_name='customer_conversations')
    op.drop_index(op.f('ix_customer_conversations_external_user_id'), table_name='customer_conversations')
    op.drop_index(op.f('ix_customer_conversations_customer_email'), table_name='customer_conversations')
    op.drop_index(op.f('ix_customer_conversations_company_id'), table_name='customer_conversations')
    op.drop_table('customer_conversations')
    # ### end Alembic commands ###
