import os

from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")
SECRET_KEY = os.getenv("SECRET_KEY")
ALGORITHM = os.getenv("ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES"))
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
SLOTELY_SUPERADMIN_SECRET = os.getenv("SLOTELY_SUPERADMIN_SECRET")
SLOTELY_SETTINGS_ENCRYPTION_KEY = os.getenv(
    "SLOTELY_SETTINGS_ENCRYPTION_KEY"
)
